version: '3.8'
services:
  mysql:
    image: mysql:8.0-bookworm
    restart: always
    container_name: zabbix-mysql
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: your_root_password
    volumes:
    - /mysql_data:/var/lib/mysql
    networks:
    - zabbix-net
  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-7.0-latest
    restart: always
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: your_password
    depends_on:
      - mysql
    ports:
      - "10051:10051"
    volumes:
      - /zabbix_server_data:/var/lib/zabbix
    networks:
      - zabbix-net
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:ubuntu-7.0-latest
    restart: always
    container_name: zabbix-java-gateway
    ports:
      - "10052:10052"
    networks:
      - zabbix-net
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-7.0-latest
    restart: always
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: your_password
      ZAB_SERVER_HOST: zabbix-server
    depends_on:
      - mysql
      - zabbix-server
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - zabbix-net
  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:ubuntu-7.0-latest
    restart: always
    container_name: zabbix-snmptraps
    volumes:
      - /snmptraps:/var/lib/zabbix/snmptraps
    networks:
      - zabbix-net
# IP address range for containers is 10.107.8.61-70/22
networks:
  zabbix-net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.107.8.0/22
         gateway: 10.107.8.1
         aux_addresses:
          mysql: 10.107.8.61
          zabbix-server: 10.107.8.62
          zabbix-java-gateway: 10.107.8.63
          zabbix-web: 10.107.8.64
          zabbix-snmptraps: 10.107.8.65
