services:
 zabbix-server:
  extends:
   file: compose_zabbix_components.yaml
   service: server-mysql
  image: zabbix-server-mysql:ubuntu-7.0-latest
  depends_on:
   - mysql-server
  labels:
   com.zabbix.os: ubuntu-7.0-latest
  zabbix-web-apache-mysql:
  extends:
   file: compose_zabbix_components.yaml
   service: web-apache-mysql
  image: zabbix-web-apache-mysql:ubuntu-7.0-latest
  depends_on:
   - mysql-server
  labels:
   com.zabbix.os: ubuntu-7.0-latest
 zabbix-java-gateway:
  extends:
   file: compose_zabbix_components.yaml
   service: java-gateway
  image: zabbix-java-gateway:ubuntu-7.0-latest
  labels:
   com.zabbix.os: ubuntu-7.0-latest
 zabbix-snmptraps:
  extends:
   file: compose_zabbix_components.yaml
   service: snmptraps
  image: zabbix-snmptraps:ubuntu-7.0-latest
  labels:
   com.zabbix.os: ubuntu-7.0-latest
 mysql-server:
  extends:
   file: compose_databases.yaml
   service: mysql-server
   
networks:
  frontend:
    driver: "bridge"
    driver_opts:
      com.docker.network.enable_ipv6: "${FRONTEND_ENABLE_IPV6}"
    ipam:
      driver: "bridge"
      config:
      - subnet: "10.107.8.0/22"
        gateway: 10.107.8.1
        aux_addresses:
         mysql: 10.107.8.61
         zabbix-server: 10.107.8.62
         zabbix-java-gateway: 10.107.8.63
         zabbix-web: 10.107.8.64
         zabbix-snmptraps: 10.107.8.65
volumes:
  snmptraps:
secrets:
  MYSQL_USER:
    file: ${ENV_VARS_DIRECTORY}/.MYSQL_USER
  MYSQL_PASSWORD:
    file: ${ENV_VARS_DIRECTORY}/.MYSQL_PASSWORD
  MYSQL_ROOT_USER:
    file: ${ENV_VARS_DIRECTORY}/.MYSQL_ROOT_USER
  MYSQL_ROOT_PASSWORD:
    file: ${ENV_VARS_DIRECTORY}/.MYSQL_ROOT_PASSWORD  
